### Word Embedding Techniques using Embedding Layer in Keras

In [108]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [109]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [110]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [111]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [112]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9139, 4022, 2881, 543], [9139, 4022, 2881, 4313], [9139, 9584, 2881, 1269], [5860, 5644, 8681, 1794, 250], [5860, 5644, 8681, 1794, 6833], [8573, 9139, 9874, 2881, 7108], [6163, 12, 3056, 1794]]


### Word Embedding Represntation

In [113]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [114]:
import numpy as np

In [115]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9139 4022 2881  543]
 [   0    0    0    0 9139 4022 2881 4313]
 [   0    0    0    0 9139 9584 2881 1269]
 [   0    0    0 5860 5644 8681 1794  250]
 [   0    0    0 5860 5644 8681 1794 6833]
 [   0    0    0 8573 9139 9874 2881 7108]
 [   0    0    0    0 6163   12 3056 1794]]


In [116]:
dim=10


In [129]:
import keras
model = Sequential()
# model.add(keras.layers.Embedding(voc_size,10,input_length=sent_length))
model.add(keras.layers.Embedding(voc_size,10))
model.compile('adam', 'mse')


ValueError: Unrecognized keyword arguments passed to Embedding: {'input_length': 8}

In [118]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [119]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
[[[ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
    4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
    2.73099057e-02  1.15172267e-02]
  [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
    4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
    2.73099057e-02  1.15172267e-02]
  [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
    4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
    2.73099057e-02  1.15172267e-02]
  [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
    4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
    2.73099057e-02  1.15172267e-02]
  [-1.53585672e-02  3.31672095e-02  1.54755451e-02 -2.42899414e-02
   -1.54434815e-02  5.36391884e-03 -2.88221836e-02 -1.48391128e-02
    2.64525414e-03 -1.40098557e-02]
  [-2.33908426e-02 -6.30257279e-03 -4.72281948e-02  4.16205786e-02
    3.54744494e-04 -3.20497155e-02  2.8059054

In [120]:
embedded_docs[0]

array([   0,    0,    0,    0, 9139, 4022, 2881,  543])

In [121]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
   4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
   2.73099057e-02  1.15172267e-02]
 [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
   4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
   2.73099057e-02  1.15172267e-02]
 [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
   4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
   2.73099057e-02  1.15172267e-02]
 [ 4.82443683e-02 -3.73999700e-02 -4.09906507e-02 -3.42641249e-02
   4.84073795e-02  3.31504680e-02  2.31507085e-02 -2.23520882e-02
   2.73099057e-02  1.15172267e-02]
 [-1.53585672e-02  3.31672095e-02  1.54755451e-02 -2.42899414e-02
  -1.54434815e-02  5.36391884e-03 -2.88221836e-02 -1.48391128e-02
   2.64525414e-03 -1.40098557e-02]
 [-2.33908426e-02 -6.30257279e-03 -4.72281948e-02  4.16205786e-02
   3.54744494e-04 -3.20497155e-02  2.80590542e-02  1.12433918