### Word Embedding Techniques using Embedding Layer in Keras

Word embeddings are a type of word representation used in natural language processing (NLP) and machine learning tasks. They are dense vector representations of words or phrases, typically generated by training a neural network model on a large corpus of text data.

In traditional NLP models, words are often represented as one-hot vectors, where each word is represented as a vector with a length equal to the size of the vocabulary, and all elements are zero except for the index corresponding to the word, which is set to one. However, one-hot representations have limitations, such as high dimensionality and inability to capture semantic relationships between words.

Word embeddings address these limitations by representing words in a continuous vector space where semantically similar words are closer together. This allows machine learning algorithms to better understand the meaning and context of words.

Popular techniques for generating word embeddings include:

1. Word2Vec: Developed by researchers at Google, Word2Vec learns word embeddings by predicting the surrounding words given a target word or vice versa. It introduces two architectures: Continuous Bag of Words (CBOW) and Skip-gram.

2. GloVe (Global Vectors for Word Representation): GloVe is another widely used word embedding technique that learns word vectors by factorizing the co-occurrence matrix of words.

3. FastText: Developed by Facebook AI Research, FastText extends the idea of word embeddings to subword units (e.g., character n-grams). It can handle out-of-vocabulary words better and capture morphological information.

4. ELMo (Embeddings from Language Models): ELMo generates word embeddings by using deep contextualized word representations. It captures word meanings based on the entire context in which the word appears.

5. BERT (Bidirectional Encoder Representations from Transformers): BERT is a transformer-based model introduced by Google that produces contextualized word embeddings by considering both left and right context of a word.

Word embeddings have revolutionized various NLP tasks, including sentiment analysis, text classification, machine translation, and named entity recognition, among others. They enable models to understand and process natural language more effectively by capturing semantic relationships between words.

In [130]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [131]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [132]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [133]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [134]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9139, 4022, 2881, 543], [9139, 4022, 2881, 4313], [9139, 9584, 2881, 1269], [5860, 5644, 8681, 1794, 250], [5860, 5644, 8681, 1794, 6833], [8573, 9139, 9874, 2881, 7108], [6163, 12, 3056, 1794]]


### Word Embedding Represntation

In [135]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [136]:
import numpy as np

In [137]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9139 4022 2881  543]
 [   0    0    0    0 9139 4022 2881 4313]
 [   0    0    0    0 9139 9584 2881 1269]
 [   0    0    0 5860 5644 8681 1794  250]
 [   0    0    0 5860 5644 8681 1794 6833]
 [   0    0    0 8573 9139 9874 2881 7108]
 [   0    0    0    0 6163   12 3056 1794]]


In [138]:
dim=10


In [139]:
import keras
model = Sequential()
# model.add(keras.layers.Embedding(voc_size,10,input_length=sent_length))
model.add(keras.layers.Embedding(voc_size,10))
model.compile('adam', 'mse')


In [140]:
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_17 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [141]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[[ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749
    0.04156742 -0.00797303 -0.04727795  0.02560146 -0.00595176]
  [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749
    0.04156742 -0.00797303 -0.04727795  0.02560146 -0.00595176]
  [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749
    0.04156742 -0.00797303 -0.04727795  0.02560146 -0.00595176]
  [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749
    0.04156742 -0.00797303 -0.04727795  0.02560146 -0.00595176]
  [ 0.01091008  0.03084356 -0.01183671 -0.00431285  0.04714154
    0.02576306  0.04124742  0.03667709 -0.02098651  0.01734051]
  [-0.03053644  0.02257584 -0.03297468 -0.04387569 -0.04957369
   -0.03963451  0.01510328 -0.04239064  0.0170014   0.04834378]
  [ 0.02608517  0.02727618  0.04560426  0.02588158 -0.00081056
    0.0315796   0.04283795 -0.04362474 -0.02920738 -0.0242644 ]
  [-0.03730259 -0.03630115  0.0019968  -0.02655239 -0.03386085
   -0.0309

In [142]:
embedded_docs[0]

array([   0,    0,    0,    0, 9139, 4022, 2881,  543])

In [143]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749  0.04156742
  -0.00797303 -0.04727795  0.02560146 -0.00595176]
 [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749  0.04156742
  -0.00797303 -0.04727795  0.02560146 -0.00595176]
 [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749  0.04156742
  -0.00797303 -0.04727795  0.02560146 -0.00595176]
 [ 0.0262043  -0.01611923 -0.03827123  0.00063157 -0.02941749  0.04156742
  -0.00797303 -0.04727795  0.02560146 -0.00595176]
 [ 0.01091008  0.03084356 -0.01183671 -0.00431285  0.04714154  0.02576306
   0.04124742  0.03667709 -0.02098651  0.01734051]
 [-0.03053644  0.02257584 -0.03297468 -0.04387569 -0.04957369 -0.03963451
   0.01510328 -0.04239064  0.0170014   0.04834378]
 [ 0.02608517  0.02727618  0.04560426  0.02588158 -0.00081056  0.0315796
   0.04283795 -0.04362474 -0.02920738 -0.0242644 ]
 [-0.03730259 -0.03630115  0.0019968  -0.02655239 -0.03386085 -0.03092271
  -0.0103241  