In TensorFlow, tensors are multi-dimensional arrays that serve as the fundamental data structure for representing data and performing operations within the framework. TensorFlow is primarily designed for deep learning and numerical computations, and tensors are at the heart of its operations.

In [28]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [29]:
import tensorflow as tf
# physical_devices = tf.config.list_physical_devices('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[0],True)

In [30]:
#initialization of Tensors
x = tf.constant(4,shape=(1,1),dtype=tf.float32) #you can also give shape and dtype
x = tf.constant([[1,2,3],[4,5,6]])
x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) #I (eye) for identity matrix
x = tf.random.normal((3,3),mean = 0,stddev = 1)
x = tf.random.uniform((1,3),minval=0,maxval = 1)
x = tf.range(start=1,limit=10,delta=2) #delta is basically step
x = tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [47]:
#Indexing
x2 = tf.constant([0,1,1,2,3,1,2,3])
print(x2[:]) 
print(x2[1:]) 
print(x2[1:3]) #from 1 to 3-1 position ie from 1 to 2 position ie 1,1 
print(x2[::2]) #skips in terms of 2 steps  
print(x2[::-1]) #reverse  

indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
print(x_ind)

x3 = tf.constant([[1,2],[3,4],[5,6]])

print(x3[0]) # or print(x3[0,:]) -> both print the first row and all the columns
print(x3[0:2,:]) #print 0 to 2-1 ie 0 to 1 position rows and all the columns 


tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [51]:
#Reshaping
x4 = tf.range(9)
print(x4)

x4 = tf.reshape(x4,(3,3))
print(x4)

x4 = tf.transpose(x4,perm=[1,0])
print(x4)


tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
